version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: password_manager_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: password_manager
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d

volumes:
  db_data:
